### ISSUE TITLE
Escape Commands solved

### ISSUE THREAD

**Issue by karwenzman** [Reijer59/TryParseHomeWorkApp#1]
Goede morgen, Reijer!

Try out some escape commands in the string varibales.

Your code
```Csharp
Console.Write("     What is your age: ");
```

Optional approach
```Csharp
Console.Write("\tWhat is your age: ");
```

![image](https://github.com/Reijer59/TryParseHomeWorkApp/assets/66565927/ea0f64c7-82e9-42b5-816c-e89638220de6)

**Comment by Reijer59** [comment]
Goedemorgen Thorsten,

I saw the issue and I will give it a try.
